//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLevel
{
    using System;
    
    public partial class CurrentUser
    {
        public int id { get; set; }
        public string login { get; set; }
        public int color32 { get; set; }
        public byte roleId { get; set; }
    }
}
