//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLevel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogUserLocked
    {
        public int userId { get; set; }
        public int userIdAdminLock { get; set; }
        public Nullable<int> userIdAdminUnlock { get; set; }
        public Nullable<byte> causeId { get; set; }
        public string anotherCause { get; set; }
        public Nullable<int> lockSpanMinutes { get; set; }
        public System.DateTime dateLock { get; set; }
        public Nullable<System.DateTime> dateUnlock { get; set; }
    
        public virtual Cause Cause { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
