//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLevel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogUserDeleted
    {
        public int idUser { get; set; }
        public System.DateTime dateDeleted { get; set; }
        public Nullable<System.DateTime> dateRecovery { get; set; }
    
        public virtual User User { get; set; }
    }
}
