//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLevel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogUserOnLine
    {
        public int userId { get; set; }
        public System.DateTime dateIn { get; set; }
        public Nullable<System.DateTime> dateOut { get; set; }
    
        public virtual User User { get; set; }
    }
}
