//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLevel
{
    using System;
    
    public partial class UnreadMessage
    {
        public int id { get; set; }
        public string text { get; set; }
        public System.DateTime date { get; set; }
        public int status { get; set; }
        public string login { get; set; }
    }
}
