//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicLevel.ChatServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseTransportModel", Namespace="http://schemas.datacontract.org/2004/07/ChatService.DataContract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicLevel.ChatServiceReference.LoginResultTransportModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicLevel.ChatServiceReference.LogoutTransportModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicLevel.ChatServiceReference.BaseHashModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicLevel.ChatServiceReference.RegistrationTransportModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicLevel.ChatServiceReference.RegistrationResultTransportModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicLevel.ChatServiceReference.MessagePartialTransportModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicLevel.ChatServiceReference.RelationTransportModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicLevel.ChatServiceReference.UserPartialTransportModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicLevel.ChatServiceReference.OnlineUserTransportModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicLevel.ChatServiceReference.UserLeavedTransportModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicLevel.ChatServiceReference.UserCollectionTransportModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicLevel.ChatServiceReference.UnreadMessagesTransportModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicLevel.ChatServiceReference.MessageTransportModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicLevel.ChatServiceReference.BlackListByUserTransportModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicLevel.ChatServiceReference.LoginTransportModel))]
    public partial class BaseTransportModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResultTransportModel", Namespace="http://schemas.datacontract.org/2004/07/ChatService.DataContract")]
    [System.SerializableAttribute()]
    public partial class LoginResultTransportModel : LogicLevel.ChatServiceReference.BaseTransportModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicLevel.ChatServiceReference.LoginResultTransport ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicLevel.ChatServiceReference.LoginResultTransport Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogoutTransportModel", Namespace="http://schemas.datacontract.org/2004/07/ChatService.DataContract")]
    [System.SerializableAttribute()]
    public partial class LogoutTransportModel : LogicLevel.ChatServiceReference.BaseTransportModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseHashModel", Namespace="http://schemas.datacontract.org/2004/07/ChatService.DataContract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicLevel.ChatServiceReference.RegistrationTransportModel))]
    public partial class BaseHashModel : LogicLevel.ChatServiceReference.BaseTransportModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] HashField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistrationTransportModel", Namespace="http://schemas.datacontract.org/2004/07/ChatService.DataContract")]
    [System.SerializableAttribute()]
    public partial class RegistrationTransportModel : LogicLevel.ChatServiceReference.BaseHashModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Color32Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> RoleIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Color32 {
            get {
                return this.Color32Field;
            }
            set {
                if ((this.Color32Field.Equals(value) != true)) {
                    this.Color32Field = value;
                    this.RaisePropertyChanged("Color32");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistrationResultTransportModel", Namespace="http://schemas.datacontract.org/2004/07/ChatService.DataContract")]
    [System.SerializableAttribute()]
    public partial class RegistrationResultTransportModel : LogicLevel.ChatServiceReference.BaseTransportModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicLevel.ChatServiceReference.RegistrationResultTransport ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicLevel.ChatServiceReference.RegistrationResultTransport Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessagePartialTransportModel", Namespace="http://schemas.datacontract.org/2004/07/ChatService.DataContract")]
    [System.SerializableAttribute()]
    public partial class MessagePartialTransportModel : LogicLevel.ChatServiceReference.BaseTransportModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicLevel.ChatServiceReference.MessageStatusTransport StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] UsersIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicLevel.ChatServiceReference.MessageStatusTransport Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] UsersId {
            get {
                return this.UsersIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersIdField, value) != true)) {
                    this.UsersIdField = value;
                    this.RaisePropertyChanged("UsersId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelationTransportModel", Namespace="http://schemas.datacontract.org/2004/07/ChatService.DataContract")]
    [System.SerializableAttribute()]
    public partial class RelationTransportModel : LogicLevel.ChatServiceReference.BaseTransportModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InitiatorUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] RelationUsersIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InitiatorUserId {
            get {
                return this.InitiatorUserIdField;
            }
            set {
                if ((this.InitiatorUserIdField.Equals(value) != true)) {
                    this.InitiatorUserIdField = value;
                    this.RaisePropertyChanged("InitiatorUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] RelationUsersId {
            get {
                return this.RelationUsersIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RelationUsersIdField, value) != true)) {
                    this.RelationUsersIdField = value;
                    this.RaisePropertyChanged("RelationUsersId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserPartialTransportModel", Namespace="http://schemas.datacontract.org/2004/07/ChatService.DataContract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LogicLevel.ChatServiceReference.OnlineUserTransportModel))]
    public partial class UserPartialTransportModel : LogicLevel.ChatServiceReference.BaseTransportModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Drawing.Color ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte RoleIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Drawing.Color Color {
            get {
                return this.ColorField;
            }
            set {
                if ((this.ColorField.Equals(value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnlineUserTransportModel", Namespace="http://schemas.datacontract.org/2004/07/ChatService.DataContract")]
    [System.SerializableAttribute()]
    public partial class OnlineUserTransportModel : LogicLevel.ChatServiceReference.UserPartialTransportModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicLevel.ChatServiceReference.UserRelationTransport RelationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicLevel.ChatServiceReference.UserRelationTransport Relation {
            get {
                return this.RelationField;
            }
            set {
                if ((this.RelationField.Equals(value) != true)) {
                    this.RelationField = value;
                    this.RaisePropertyChanged("Relation");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserLeavedTransportModel", Namespace="http://schemas.datacontract.org/2004/07/ChatService.DataContract")]
    [System.SerializableAttribute()]
    public partial class UserLeavedTransportModel : LogicLevel.ChatServiceReference.BaseTransportModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserCollectionTransportModel", Namespace="http://schemas.datacontract.org/2004/07/ChatService.DataContract")]
    [System.SerializableAttribute()]
    public partial class UserCollectionTransportModel : LogicLevel.ChatServiceReference.BaseTransportModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicLevel.ChatServiceReference.OnlineUserTransportModel[] UsersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicLevel.ChatServiceReference.OnlineUserTransportModel[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnreadMessagesTransportModel", Namespace="http://schemas.datacontract.org/2004/07/ChatService.DataContract")]
    [System.SerializableAttribute()]
    public partial class UnreadMessagesTransportModel : LogicLevel.ChatServiceReference.BaseTransportModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicLevel.ChatServiceReference.MessageTransportModel[] MessagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicLevel.ChatServiceReference.MessageTransportModel[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageTransportModel", Namespace="http://schemas.datacontract.org/2004/07/ChatService.DataContract")]
    [System.SerializableAttribute()]
    public partial class MessageTransportModel : LogicLevel.ChatServiceReference.BaseTransportModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LogicLevel.ChatServiceReference.MessageStatusTransport StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicLevel.ChatServiceReference.MessageStatusTransport Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlackListByUserTransportModel", Namespace="http://schemas.datacontract.org/2004/07/ChatService.DataContract")]
    [System.SerializableAttribute()]
    public partial class BlackListByUserTransportModel : LogicLevel.ChatServiceReference.BaseTransportModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InitiatorUserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InitiatorUserId {
            get {
                return this.InitiatorUserIdField;
            }
            set {
                if ((this.InitiatorUserIdField.Equals(value) != true)) {
                    this.InitiatorUserIdField = value;
                    this.RaisePropertyChanged("InitiatorUserId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginTransportModel", Namespace="http://schemas.datacontract.org/2004/07/ChatService.DataContract")]
    [System.SerializableAttribute()]
    public partial class LoginTransportModel : LogicLevel.ChatServiceReference.BaseTransportModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] HashField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResultTransport", Namespace="http://schemas.datacontract.org/2004/07/ChatService.DataContract")]
    public enum LoginResultTransport : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ok = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lock = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Online = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fail = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistrationResultTransport", Namespace="http://schemas.datacontract.org/2004/07/ChatService.DataContract")]
    public enum RegistrationResultTransport : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ok = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Login = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageStatusTransport", Namespace="http://schemas.datacontract.org/2004/07/ChatService.DataContract")]
    public enum MessageStatusTransport : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Private = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Friend = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Share = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRelationTransport", Namespace="http://schemas.datacontract.org/2004/07/ChatService.DataContract")]
    public enum UserRelationTransport : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Friend = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Blacklist = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChatServiceReference.IChatService", CallbackContract=typeof(LogicLevel.ChatServiceReference.IChatServiceCallback))]
    public interface IChatService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/Login", ReplyAction="http://tempuri.org/IChatService/LoginResponse")]
        LogicLevel.ChatServiceReference.LoginResultTransportModel Login(LogicLevel.ChatServiceReference.LoginTransportModel obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/Login", ReplyAction="http://tempuri.org/IChatService/LoginResponse")]
        System.Threading.Tasks.Task<LogicLevel.ChatServiceReference.LoginResultTransportModel> LoginAsync(LogicLevel.ChatServiceReference.LoginTransportModel obj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/Logout")]
        void Logout(LogicLevel.ChatServiceReference.LogoutTransportModel obj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/Logout")]
        System.Threading.Tasks.Task LogoutAsync(LogicLevel.ChatServiceReference.LogoutTransportModel obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/Registration", ReplyAction="http://tempuri.org/IChatService/RegistrationResponse")]
        LogicLevel.ChatServiceReference.RegistrationResultTransportModel Registration(LogicLevel.ChatServiceReference.RegistrationTransportModel obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/Registration", ReplyAction="http://tempuri.org/IChatService/RegistrationResponse")]
        System.Threading.Tasks.Task<LogicLevel.ChatServiceReference.RegistrationResultTransportModel> RegistrationAsync(LogicLevel.ChatServiceReference.RegistrationTransportModel obj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/SendMessage")]
        void SendMessage(LogicLevel.ChatServiceReference.MessagePartialTransportModel obj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/SendMessage")]
        System.Threading.Tasks.Task SendMessageAsync(LogicLevel.ChatServiceReference.MessagePartialTransportModel obj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/AddBlackList")]
        void AddBlackList(LogicLevel.ChatServiceReference.RelationTransportModel obj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/AddBlackList")]
        System.Threading.Tasks.Task AddBlackListAsync(LogicLevel.ChatServiceReference.RelationTransportModel obj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/RemoveBlackList")]
        void RemoveBlackList(LogicLevel.ChatServiceReference.RelationTransportModel obj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/RemoveBlackList")]
        System.Threading.Tasks.Task RemoveBlackListAsync(LogicLevel.ChatServiceReference.RelationTransportModel obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/UserJoin")]
        void UserJoin(LogicLevel.ChatServiceReference.OnlineUserTransportModel obj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/UserLeave")]
        void UserLeave(LogicLevel.ChatServiceReference.UserLeavedTransportModel obj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/MessageReceived")]
        void MessageReceived(LogicLevel.ChatServiceReference.MessagePartialTransportModel obj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/OnlineUsers")]
        void OnlineUsers(LogicLevel.ChatServiceReference.UserCollectionTransportModel obj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/CurrentUser")]
        void CurrentUser(LogicLevel.ChatServiceReference.UserPartialTransportModel obj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/UnreadMessages")]
        void UnreadMessages(LogicLevel.ChatServiceReference.UnreadMessagesTransportModel obj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/AddBlackListByUser")]
        void AddBlackListByUser(LogicLevel.ChatServiceReference.BlackListByUserTransportModel obj);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/RemoveBlackListByUser")]
        void RemoveBlackListByUser(LogicLevel.ChatServiceReference.BlackListByUserTransportModel obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatServiceChannel : LogicLevel.ChatServiceReference.IChatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatServiceClient : System.ServiceModel.DuplexClientBase<LogicLevel.ChatServiceReference.IChatService>, LogicLevel.ChatServiceReference.IChatService {
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public LogicLevel.ChatServiceReference.LoginResultTransportModel Login(LogicLevel.ChatServiceReference.LoginTransportModel obj) {
            return base.Channel.Login(obj);
        }
        
        public System.Threading.Tasks.Task<LogicLevel.ChatServiceReference.LoginResultTransportModel> LoginAsync(LogicLevel.ChatServiceReference.LoginTransportModel obj) {
            return base.Channel.LoginAsync(obj);
        }
        
        public void Logout(LogicLevel.ChatServiceReference.LogoutTransportModel obj) {
            base.Channel.Logout(obj);
        }
        
        public System.Threading.Tasks.Task LogoutAsync(LogicLevel.ChatServiceReference.LogoutTransportModel obj) {
            return base.Channel.LogoutAsync(obj);
        }
        
        public LogicLevel.ChatServiceReference.RegistrationResultTransportModel Registration(LogicLevel.ChatServiceReference.RegistrationTransportModel obj) {
            return base.Channel.Registration(obj);
        }
        
        public System.Threading.Tasks.Task<LogicLevel.ChatServiceReference.RegistrationResultTransportModel> RegistrationAsync(LogicLevel.ChatServiceReference.RegistrationTransportModel obj) {
            return base.Channel.RegistrationAsync(obj);
        }
        
        public void SendMessage(LogicLevel.ChatServiceReference.MessagePartialTransportModel obj) {
            base.Channel.SendMessage(obj);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(LogicLevel.ChatServiceReference.MessagePartialTransportModel obj) {
            return base.Channel.SendMessageAsync(obj);
        }
        
        public void AddBlackList(LogicLevel.ChatServiceReference.RelationTransportModel obj) {
            base.Channel.AddBlackList(obj);
        }
        
        public System.Threading.Tasks.Task AddBlackListAsync(LogicLevel.ChatServiceReference.RelationTransportModel obj) {
            return base.Channel.AddBlackListAsync(obj);
        }
        
        public void RemoveBlackList(LogicLevel.ChatServiceReference.RelationTransportModel obj) {
            base.Channel.RemoveBlackList(obj);
        }
        
        public System.Threading.Tasks.Task RemoveBlackListAsync(LogicLevel.ChatServiceReference.RelationTransportModel obj) {
            return base.Channel.RemoveBlackListAsync(obj);
        }
    }
}
